=== OpenConext/OpenConext-manage/manage-server/src/main/resources/metadata_configuration/institution.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "institution",
  "order": 11,
  "type": "object",
  "properties": {
    "eid": {
      "type": "number"
    },
    "entityid": {
      "type": "string",
      "minLength": 1
    },
    "identifier": {
      "type": "string",
      "info": "The unique identifier of the institution."
    },
    "use_ra_locations": {
      "type": "boolean"
    },
    "show_raa_contact_information": {
      "type": "boolean"
    },
    "verify_email": {
      "type": "boolean"
    },
    "sso_registration_bypass": {
      "type": "boolean"
    },
    "allowed_second_factors": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "yubikey",
          "tiqr",
          "webauthn",
          "sms",
          "azuremfa"
        ]
      }
    },
    "number_of_tokens_per_identity": {
      "type": "number"
    },
    "use_ra": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "use_raa": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "select_raa": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "self_vet": {
      "type": "boolean"
    },
    "allow_self_asserted_tokens": {
      "type": "boolean"
    },
    "sso_on_2fa": {
      "type": "boolean"
    },
    "stepup-client": {
      "type": "string",
      "enum": [
        "freerider",
        "full",
        "freerider met azuremfa"
      ],
      "default": "freerider"
    },

    "revisionid": {
      "type": "number"
    },
    "created": {
      "type": [
        "string",
        "null"
      ]
    },
    "revisionnote": {
      "type": "string"
    },
    "notes": {
      "type": [
        "string",
        "null"
      ]
    },
    "metaDataFields": {
      "type": "object",
      "properties": {},
      "patternProperties": {},
      "required": [],
      "additionalProperties": false
    }
  },
  "required": [
    "entityid",
    "identifier",
    "stepup-client"
  ],
  "additionalProperties": false,
  "indexes": []
}

=== OpenConext/OpenConext-manage/manage-server/src/main/resources/metadata_templates/institution.template.json
{
  "entityid": "",
  "metaDataFields": {},
  "identifier": "",
  "use_ra_locations": true,
  "show_raa_contact_information": true,
  "verify_email": true,
  "allowed_second_factors": [
    "tiqr"
  ],
  "number_of_tokens_per_identity": 3,
  "use_ra": [],
  "use_raa": [],
  "select_raa": [],
  "self_vet": true,
  "allow_self_asserted_tokens": false,
  "sso_registration_bypass": false,
  "sso_on_2fa": false,
  "stepup-client": "full"
}
